minor revisions
- updated README content and structure
- updated logic in action.yml
- simplified code on msg function
- removed bunsh.config since building local via script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,18 +1,42 @@
 name: 'gha-setup'
-description: 'installs the latest gha commands for use in the current workflow job'
-
+description: 'installs gha commands for use in the current workflow job'
+author: 'Kamaran Layne'
+branding:
+  icon: 'command'
+  color: 'gray-dark'
+inputs:
+  version:
+    description: |
+      Version to install.
+      Default: 'latest'
+    default: latest
+    required: false
 runs:
   using: composite
   steps:
-
-    - run: mkdir -p "$RUNNER_TEMP/_gha"
-      shell: bash
-
     - run: |
-        VER="$(curl -sL 'https://raw.githubusercontent.com/KamaranL/gha/main/VERSION.txt')" && {
-            curl -sL "https://github.com/KamaranL/gha/releases/download/v$VER/gha-v$VER.tgz" | tar -xz -C .
-            chmod -R +x .
-            ./core add-path "$PWD"
+        # setup
+        [ "$VERSION" == latest ] && {
+            VERSION="$(curl -sL "https://raw.githubusercontent.com/$ACTION_REPOSITORY/main/VERSION.txt")"
+            echo "::debug::Using latest version: $VERSION"
         }
+        RELEASE_URL="https://github.com/$ACTION_REPOSITORY/releases/download/v$VERSION/${ACTION_REPOSITORY##*\/}-v$VERSION.tgz"
+        STATUS_CODE="$(curl -sI -o /dev/null -w "%{http_code}" -L "$RELEASE_URL")" &&
+            ((STATUS_CODE != 200)) && {
+            echo "::error::($STATUS_CODE) Specified version unavailable: v$VERSION"
+            exit 1
+        }
+
+        [ ! -d "$ACTION_REPOSITORY" ] && mkdir -p "$ACTION_REPOSITORY"
+        pushd "$ACTION_REPOSITORY" >/dev/null 2>&1
+        echo "::debug::Downloading packaged release: $RELEASE_URL"
+        curl -sL "$RELEASE_URL" | tar -xz -C .
+        chmod -R +x bin
+        echo "::debug::Appending to path: $PWD/bin"
+        echo "$PWD/bin" >>"$GITHUB_PATH"
+        popd >/dev/null 2>&1
       shell: bash
-      working-directory: ${{ runner.temp }}/_gha
+      working-directory: ${{ runner.temp }}
+      env:
+        ACTION_REPOSITORY: ${{ github.action_repository }}
+        VERSION: ${{ inputs.version }}
